### ISSUE TITLE
Otter export failed due to a chinese font Issue! 

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#2714] opened 2021-09-07 16:35 UTC
### Bug description

Data 100 team reported this error through their Piazza channel over the weekend!

(/usr/share/texlive/texmf-dist/tex/latex/titling/titling.sty)
(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)
(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)
(/usr/share/texlive/texmf-dist/tex/latex/enumitem/enumitem.sty)
(/usr/share/texlive/texmf-dist/tex/generic/ulem/ulem.sty)
(/usr/share/texlive/texmf-dist/tex/latex/jknapltx/mathrsfs.sty)kpathsea:make_tex: Invalid filename `[FandolSong-Regular.otf]/OT', contains '['

Package xeCJK Warning: Fandol is being set as the default font for CJK text.
(xeCJK)                Please make sure it has been properly installed.

! Package fontspec Error: The font "FandolSong-Regular" cannot be found.

For immediate help type H <return>.
 ...                                              
                                                  
l.307 \begin{document}
                      
? 
! Emergency stop.
 ...                                              
                                                  
l.307 \begin{document}
                      
No pages of output.
Transcript written on notebook.log.
I looked into this and this font is in the package texlive-lang-chinese, so a apt install texlive-lang-chinese? But it seems strange to need a Chinese font for this. Any thoughts?

### Environment & setup

- Hub:  Data 100

### How to reproduce

@chrispyles suggestion to fix this issue - https://github.com/ucbds-infra/otter-grader/blob/master/Dockerfile#L45-L51

**Comment by felder** [comment] 2021-09-07 18:29
Yeah this error is quite confusing.  The issue is the font is actually missing, but the error suggests the name is wrong.

Apparently when a font is missing, tex defaults to another name.

I think the solution of apt installing texlive-lang-chinese is the right way to go:

https://packages.ubuntu.com/focal/all/texlive-lang-chinese/filelist

```
/usr/share/texlive/texmf-dist/fonts/opentype/public/fandol/FandolSong-Bold.otf
/usr/share/texlive/texmf-dist/fonts/opentype/public/fandol/FandolSong-Regular.otf
```

If that fails, I can look into the solution outlined by @chrispyles

**Comment by felder** [comment] 2021-09-08 17:24
I went here:
https://data100.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2FDS-100%2Ffa21&urlpath=lab%2Ftree%2Ffa21%2Fhw%2Fhw2%2Fhw2.ipynb&branch=main

opened a terminal and ran:
```
jovyan@jupyter-felder:~$ cd fa21/hw/hw2/
jovyan@jupyter-felder:~/fa21/hw/hw2$ otter export hw2.ipynb out.pdf
jovyan@jupyter-felder:~/fa21/hw/hw2$
```

out.pdf was created with no errors reported, so I assume that means this is fixed.

**Comment by balajialg** [comment] 2021-09-08 17:56
Input from Data 100 User Anirudh!

**Ah sorry wasn't aware that you were unfamiliar. You would have to run the very first cell at least to run the last one. It does seem to have worked. Thank you!**

Closing this issue as a result. Thanks @felder

**Comment by champoll** [comment] 2021-09-08 20:06
I think this issue should be reopened. After upgrading otter from 3.0.6 to 3.1.1, a notebook that previously compiled without problems (using otter assign) no longer did so. I ran into the same issue and was unable to fix it using the method at https://github.com/ucbds-infra/otter-grader/blob/master/Dockerfile#L45-L51 because I don't have rights to write to /usr/share. Running the first cell of the notebook prior to compiling did not help either.

**Comment by felder** [comment] 2021-09-08 20:12
@champoll can you give you me steps to reproduce the issue you're talking about?

**Comment by fperez** [comment] 2021-09-08 21:00
Thx for the report @champoll! Can you point us to the notebook that is giving you trouble so we can try to track this down?

**Comment by champoll** [comment] 2021-09-08 22:04
[assignment01-Copy1.ipynb.zip](https://github.com/berkeley-dsep-infra/datahub/files/7132035/assignment01-Copy1.ipynb.zip)
To reproduce, run "otter assign assignment01-Copy1.ipynb dist".

Running Python 3.8.5.

```
(otter-env) instructor@jupyter-lc126:~$ latex --version
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)
kpathsea version 6.3.1
Copyright 2019 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.01
```

**Comment by felder** [comment] 2021-09-08 22:08
@champoll what hub are you doing this on?  Your environment does not look typical for one of our hubs.

**Comment by champoll** [comment] 2021-09-08 22:10
It's on an instance of Jupyterhub provided by my university (NYU). Is there a command I can run whose output would help you?

**Comment by felder** [comment] 2021-09-08 22:12
@champoll are you perhaps commenting in the wrong issue?  This issue is specific to UC Berkeley managed jupyterhubs.

If you're referring to an issue with otter, that is not managed by this team.  You'd need to open an issue with the otter team.  Perhaps https://github.com/ucbds-infra/otter-grader ?

Alternatively if the issue is with a missing font, you'd need to contact whomever is responsible for image management of jupyterhubs at your university.

**Comment by champoll** [comment] 2021-09-08 22:15
Oh sorry! I was on the wrong github. I'll open an issue on the otter github.

**Comment by felder** [comment] 2021-09-08 22:16
@champoll ok no worries, closing.

**Closed as completed by felder** 2021-09-08 22:16 UTC
Labels: bug, package-request

**Comment by balajialg** [comment] 2021-09-08 22:29
@felder @yuvipanda @ericvd-ucb This is something to consider from a support process perspective (For us and Otter). For a new user, it may be hard to differentiate whether an issue is because of otter/jupyterhubs service. This has happened at least 3 times in the past 2/3 weeks.

**Comment by felder** [comment] 2021-09-08 22:33
@balajialg yes it's been a consistent issue which I think we need to somehow clarify as part of our support process.  Additionally I think it would be wise to have a representative of the otter team as well as the data8x team be present at some if not all of our operational meetings.

In addition to the otter vs jupyterhub support confusion, we probably could use better coordination from the teams as we've had a number of support requests with high immediacy due to otter issues which ideally would be QA'd in some way before being released.

**Comment by balajialg** [comment] 2021-09-09 00:31
@felder Yes, If we all think this is a consistent challenge and believe there has to be a better way of doing this. 
Then, I am thinking, why not have a common Tier I support system for otter and jupyterhub to start with. Then, if someone could parse such requests and redirect them to the relevant folks, that could be valuable for our users and for both the team.

**Comment by ericvd-ucb** [comment] 2021-09-09 02:40
FWIW I was just talkign to the Otter team - and they want people to send issues to the Otter slack where multiple people can check. them out

**Comment by chrispyles** [comment] 2021-09-09 02:47
Or (for bugs etc. as opposed to more general questions), preferably open a issue on the Otter repo: https://github.com/ucbds-infra/otter-grader

**Comment by balajialg** [comment] 2021-09-09 21:43
thanks, @ericvd-ucb, and @chrispyles!

@chrispyles Just a suggestion, It would be helpful to figure out a way where the team here gets a short update on the future otter releases. It will make things easy from the perspective that we can quickly escalate the issues to the Otter channel when we have a better intuition of the changes that got made in the recent release. Eg: Otter latex requiring fandol template!
