### ISSUE TITLE
Shared folders not sync with other GSIs

### ISSUE THREAD

**Issue by caroluscha** [berkeley-dsep-infra/hubs#6469] opened 2024-11-08 19:40 UTC
### Bug description

Recently, we requested a shared folders to share data with our students. Specifically, `IB134L-shared-readwrite` and `IB134L-shared`. I upload files to the readwrite folder but the other GSIs are unable to see them. Strangely, it was there before and then disappeared. I reuploaded them but doesn't seem to by syncing. 

### Environment & setup

- Hub: 
- Language: 
biology.datahub.edu IB134L

### How to reproduce

Uploaded files to `IB134L-shared-readwrite`.  It's not showing up in other GSIs `IB134L-shared-readwrite`

**Comment by balajialg** [comment] 2024-11-08 20:36
@caroluscha That's weird - We haven't encountered this issue before. I reviewed https://bcourses.berkeley.edu/courses/1536425 site and found that all the TA's are affiliated to both TA and student roles. Can all the TA's try to remove themselves from the student role in bcourses, log out of the bio hub and then log back in and see if the shared directory works as expected?

**Comment by felder** [comment] 2024-11-08 20:36
@caroluscha it looks to me like you uploaded files directly to your home directory as opposed to the shared folder, this suggests to me that the shared folder is not being mounted for you when you sign in.

Two things might cause that issue.

1.  You're not in the ta or teacher group as designated in bcourses.  In which case you need to add yourself to one of them.
2. You're in both groups in which case you need to remove yourself from one of them.

I've moved the files you wrote to the right place and they should show up for the other GSIs.  If they don't show up for you, that would confirm that one of the above two issues is occurring.

**Comment by balajialg** [comment] 2024-11-08 20:37
@felder Yes, they are in both the groups!

**Comment by felder** [comment] 2024-11-08 20:41
@caroluscha while I'm in here I see that there are files associated with this course stored in _shared/IB134L_data which you cannot see and which as the system is currently configured no one can see.  I'm going to move those as well.

**Comment by felder** [comment] 2024-11-08 21:08
Also noting that the shared directories are misconfigured essentially the files tas and teachers write would never be seen by students as configured.  While related to your issue, it's not the cause of your issue. :)

**Comment by caroluscha** [comment] 2024-11-08 21:27
ok I removed myself as a student on bcourses and logged back into the biology.datahub. Am I suppose to be able to see a copy of files I uploaded into the readwrite folder in the shared folder?

**Comment by caroluscha** [comment] 2024-11-08 23:10
So I uploaded some files to the readwrite folder and my other TAs are not seeing the files.

**Comment by balajialg** [comment] 2024-11-08 23:49
@caroluscha Would you be okay for a short zoom call to debug? The changes are not yet merged to prod - https://github.com/berkeley-dsep-infra/datahub/pull/6471. You can try testing with https://biology-staging.datahub.berkeley.edu/ and see if everything works.

**Comment by caroluscha** [comment] 2024-11-08 23:55
Yeah that's fine.

**Comment by felder** [comment] 2024-11-09 02:43
I believe all of this is now fixed.

When instructors login they should see a directory named "IB134L-shared-readwrite" that leads directly to the uploaded files and they should be able to make changes there. They should also see a directory named "shared" which will contain several other things including shared/courses/IB134L-shared, however they will not be able to make changes there.

Similarly students should see a directory named IB134L-shared that leads directly to the uploaded files, but they will not be able to make changes.  They should also see a directory named "shared" which will contain several other things including shared/courses/IB134L-shared, however they will not be able to make changes there.

Students should be advised to use IB134L-shared and instructors should be advised to use IB134L-shared-readwrite.

I hope this clears all this up.  Please let me know if you continue to have problems.

**Closed as completed by felder** 2024-11-09 02:43 UTC
Labels: bug
