### ISSUE TITLE
Request python package [pymatgen, matminer] for LBL summer research internship

### ISSUE THREAD

**Issue by enze-chen** [berkeley-dsep-infra/hubs#2409] opened 2021-05-26 19:59 UTC
**Which package do you want installed?**

I would like to install `pymatgen==2020.10.20` and `matminer==0.6.5`.

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**

This is a summer internship through LBL (no class number) and DataHub is linked through a Jupyter Book, so I think the main DataHub is the best option.

**Which class will use this package?**

The class is a 3-week summer research internship on materials informatics. The instructors are PhD student [Enze Chen](https://enze-chen.github.io/) and MSE Professor [Mark Asta](https://mse.berkeley.edu/people_new/asta/). The course will use a Jupyter Book hosted at: https://enze-chen.github.io/mi-book/

**Which semester will this package be used for?**

For now, just Summer 2021.

**Any additional information we should know about?**

Currently when I try to install these two packages with `pip` on DataHub, the installation goes through and I can use the packages to do what I need without apparent conflicts. But upon import, I do get the following warning:
```bash
/opt/conda/lib/python3.8/site-packages/geopandas/_compat.py:106: UserWarning: The Shapely GEOS version (3.8.0-CAPI-1.13.1 ) is incompatible with the GEOS version PyGEOS was compiled with (3.9.0-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
```

**Comment by enze-chen** [comment] 2021-05-26 20:43
Also submitted PR #2410

**Comment by felder** [comment] 2021-06-01 23:46
@enze-chen was there a particular reason why you chose this version of pymatgen as opposed to the latest?

https://pypi.org/project/pymatgen/
https://pymatgen.org/change_log.html

**Comment by enze-chen** [comment] 2021-06-02 00:21
Hi! Yes, I chose this one because at least when I naively used `pip` to install the latest version, it also forced me to upgrade `numpy` and a few other packages in the default DataHub packages. I wanted to minimize the damage, and this version still allows for everything we wanted to teach. But feel free to use a newer version if that is better practice; I have written the code such that it avoids the breaking changes and works with all recent versions (_I think..._).

**Comment by felder** [comment] 2021-06-02 17:08
@enze-chen fair enough, I just wanted to be certain the earlier version was intended before I merge it. :)

**Comment by felder** [comment] 2021-06-02 19:02
Merged to prod.

**Closed as completed by felder** 2021-06-02 19:02 UTC
Labels: support
