### ISSUE TITLE
R Datahub 505 Internal Service Error

### ISSUE THREAD

**Issue by andrewpbray** [berkeley-dsep-infra/hubs#3166] opened 2022-01-20 14:10 UTC
### Bug description

When logging into R DataHub this morning, I encountered a 505 Internal Service Error. Today is the first day of labs in Stat 20; 650 students will be trying to log into this hub throughout the day.

<img width="1298" alt="Screen Shot 2022-01-20 at 6 07 03 AM" src="https://user-images.githubusercontent.com/1627362/150354469-810973bf-4bd0-4f48-afbd-809e07035a80.png">

### Environment & setup

- Hub: Datahub
- Language: R

### How to reproduce

1. Log into r.datahub.berkeley.edu.

**Comment by andrewpbray** [comment] 2022-01-20 14:13
## Follow-up

Starting and re launching server results in the same error message.

**Comment by yuvipanda** [comment] 2022-01-20 15:44
@andrewpbray looking at it now.

**Comment by yuvipanda** [comment] 2022-01-20 15:50
Hmm, stat20.datahub.berkeley.edu is working fine while the RStudio in r.datahub.berkeley.edu is not. Am investigating now.

**Comment by andrewpbray** [comment] 2022-01-20 15:52
Thanks.

@ryanlovett is stat20.datahub.berkeley.edu ready to go or should we stick to r.datahub.berkeley.edu? I'm not inclined to switch once we send students to one or the other.

**Comment by yuvipanda** [comment] 2022-01-20 15:54
@andrewpbray the stat20 hub is ready, I'd suggest starting there.

**Comment by andrewpbray** [comment] 2022-01-20 15:56
Will do.

**Comment by yuvipanda** [comment] 2022-01-20 16:01
@andrewpbray r datahub also fixed right now. I'm investigating the cause, but should be usable now. For you, I'd still suggest using the stat20 hub though.

**Comment by andrewpbray** [comment] 2022-01-20 16:04
Thanks. Labs are just starting right now, so we've committed to the stat20 hub. I'll be interested to learn what the issue was.

**Comment by andrewpbray** [comment] 2022-01-20 16:11
@yuvipanda

From a GSI: I could not log onto stat20.datahub.berkeley.edu. But r.datahub.berkeley.edu works for me!
From another GSI: I tried on incognito and it works for me!

**Comment by yuvipanda** [comment] 2022-01-20 16:16
@andrewpbray yeah, fixing that right now.

**Comment by yuvipanda** [comment] 2022-01-20 16:18
@andrewpbray try again now for stat20? It broke when fixing R datahub.

Really sorry about the inconcenience!

**Comment by yuvipanda** [comment] 2022-01-20 16:18
Sorry, still fixing it looks like.

**Comment by yuvipanda** [comment] 2022-01-20 16:22
@andrewpbray ok fixed for real now. Can you try again?

**Comment by andrewpbray** [comment] 2022-01-20 16:24
@yuvipanda I've asked the GSIs to try (I was able to log into stat 20) but they're teaching right now so I haven't heard back on staff slack.

**Comment by yuvipanda** [comment] 2022-01-20 16:25
@andrewpbray alright. Really sorry about the issue!

**Comment by andrewpbray** [comment] 2022-01-20 16:29
@yuvipanda @ryanlovett This is the second semester in a row that this has happened: hundreds of students getting their first introduction to computing and a dozen GSIs trying to teach over Zoom with unreliable technology. I'd like to discuss how we can develop a protocol to prevent this from happening.

**Comment by balajialg** [comment] 2022-01-20 19:09
@andrewpbray I am the Service Lead for Datahub. Really sorry for the inconvenience caused to the instruction today! @ryanlovett will set up a meeting between you and our team where we can discuss the details of the protocol to ensure that such changes don't affect the experience of the GSIs and students. Once again, personally and on behalf of the Datahub team, apologize for the mishap today and want to highlight that we are committed to ensuring that such issues will not replicate in the future.

**Comment by balajialg** [comment] 2022-01-25 19:04
Closing this issue as it got resolved!

**Closed as completed by balajialg** 2022-01-25 19:04 UTC
Labels: bug
