### ISSUE TITLE
Upgrade to z2jh 1.0

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/hubs#2427] opened 2021-06-15 11:47 UTC
Zero to JupyterHub 1.0 has been released - https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/CHANGELOG.md#10.

We should upgrade to it!

**Comment by felder** [comment] 2021-06-17 19:34
cs194 has the following error:
- prePuller.extraImages.postgres: Additional property policy is not allowed

Here's the offending snippit from cs194/config/common.yaml:
```
    extraImages:
      postgres:
        name: gcr.io/ucb-datahub-2018/jupyterhub-postgres
        tag: 0.0.1-n3657.h4f7f88c
        policy: IfNotPresent
```
@yuvipanda how should we deal with this `policy: IfNotPresent` config?

**Comment by felder** [comment] 2021-06-17 19:59
Confirmed that memory limits set via #2432 work in datahub-staging.

**Comment by yuvipanda** [comment] 2021-06-17 20:22
@felder i think you can get rid of the policy. IfNotPresent is the default, not sure why it was specified earlier

**Comment by felder** [comment] 2021-06-17 20:44
Verified admin privileges are still assigned properly for dlab-staging.

**Comment by felder** [comment] 2021-06-17 21:21
hmm...data100 is timing out on the deploy:

```
Error: UPGRADE FAILED: timed out waiting for the condition
Traceback (most recent call last):
  File "/root/repo/venv/bin/hubploy", line 8, in <module>
    sys.exit(main())
  File "/root/repo/venv/lib/python3.7/site-packages/hubploy/__main__.py", line 140, in main
    args.cleanup_on_fail,
  File "/root/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 189, in deploy
    cleanup_on_fail,
  File "/root/repo/venv/lib/python3.7/site-packages/hubploy/helm.py", line 102, in helm_upgrade
    subprocess.check_call(cmd)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['helm', 'upgrade', '--wait', '--install', '--namespace', 'data100-staging', 'data100-staging', 'hub', '-f', 'deployments/data100/config/common.yaml', '-f', 'deployments/data100/config/staging.yaml', '-f', '/tmp/tmpxavuosx5', '--set-string', 'jupyterhub.singleuser.image.tag=0aab0f1', '--set-string', 'jupyterhub.singleuser.image.name=gcr.io/ucb-datahub-2018/primary-user-image']' returned non-zero exit status 1.

Exited with code exit status 1
```

I sent it through a couple times.  Maybe CircleCI needs a break, I'll revisit this in a bit.

**Comment by felder** [comment] 2021-06-18 00:51
@yuvipanda yeah data100 doesn't wanna go

**Comment by felder** [comment] 2021-06-18 18:36
Yuvi pointed me to kubectl saying that the deployment can timeout/fail if stuff fails to start.  kubectl reveals that the hub pod is errorring out because the fetch-emails-sidecar is unhappy.  

```
(datahub-venv) MacBook-Pro-Work:datahub felder$ kubectl --namespace=data100-staging get pods | grep hub
hub-6f7fcdc8cc-47xb4              1/2     CrashLoopBackOff   7          15m
(datahub-venv) MacBook-Pro-Work:datahub felder$ kubectl --namespace=data100-staging logs hub-6f7fcdc8cc-47xb4 fetch-course-emails
Traceback (most recent call last):
  File "/usr/local/bin/course-emails.py", line 183, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/bin/course-emails.py", line 171, in main
    profiles = read_profiles(args.values)
  File "/usr/local/bin/course-emails.py", line 100, in read_profiles
    return list(values['custom']['profiles'].keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```

@ryanlovett when you have a chance, can you please take a look?

**Comment by ryanlovett** [comment] 2021-06-21 19:37
@felder Fixed! It is now on workshop/nodeSelector.

**Comment by felder** [comment] 2021-06-24 23:30
Yuvi merged this to prod and it has been running there for a while.

**Closed as completed by felder** 2021-06-24 23:30 UTC
