### ISSUE TITLE
Recover old files

### ISSUE THREAD

**Issue by irisk2050** [berkeley-dsep-infra/hubs#3266] opened 2022-02-15 21:52 UTC
### Email Id

minjeekim303@berkeley.edu

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/minjeekim303.tar.gz

**Comment by felder** [comment] 2022-02-15 22:00
I assume this is a duplicate of #3258.

Please update the ticket there with the information requested.

**Closed as completed by felder** 2022-02-15 22:00 UTC
Labels: support
