### ISSUE TITLE
Data 8 Datahub Admin Access Request

### ISSUE THREAD

**Issue by sarsong** [berkeley-dsep-infra/hubs#5358] opened 2024-01-10 21:00 UTC
### Your Name

Sarah Song

### Affiliated Course Name

Data 8

### Bcourses Id

1532352

### Role

Lead TA

### Name of the Hub

Data 8

### End Date

05/17/24

### Request Deadline

01/16/24

**Comment by balajialg** [comment] 2024-01-11 19:27
@sarsong The changes are merged to staging. I will give a heads-up once the changes are live in production.

**Comment by balajialg** [comment] 2024-01-17 17:26
@sarsong Changes should be live in data8.datahub.b.e. Please reopen this issue if there are any discrepancies!

**Closed as completed by balajialg** 2024-01-17 17:26 UTC
Labels: support

**Comment by atticusginsborg** [comment] 2024-01-31 00:57
Hi Balaji my name is Atticus Ginsborg and I'm one of the uGSI's for Data 8. Not sure what happened but I went to log into data8 datahub as an admin and it wouldn't let me. Please let me know what I need to do to get added.

**Comment by balajialg** [comment] 2024-01-31 01:17
@atticusginsborg That is weird. You already seem to have elevated privileges provisioned for course staff in Data 8 Hub (Ref: snapshot below). Can other course staff access their elevated privileges?


<img width="1156" alt="image" src="https://github.com/berkeley-dsep-infra/datahub/assets/2306166/6a67372a-a376-45a9-9ef9-276cc1745c6a">

**Comment by atticusginsborg** [comment] 2024-01-31 01:33
@balajialg as far as I can tell all other course staff are able to access their elevated privileges but it's possible some just haven't checked recently as we don't need it often. All I know is when I try going to the admin link like normal I get the error in the screenshot below. I can ask that other staff verify they can access their privileges if you'd like.
![image](https://github.com/berkeley-dsep-infra/datahub/assets/70498442/cb5c5b8e-7b49-46d2-af8e-05dbbefd9597)

**Comment by balajialg** [comment] 2024-01-31 01:36
Got it, thanks @atticusginsborg! Please report the status of other staff too. 

I have tried a fix via #5478. Let's see whether that works!

**Comment by atticusginsborg** [comment] 2024-01-31 01:46
@balajialg it worked for me! Enquiring about other staff and will get back to you.

**Comment by balajialg** [comment] 2024-01-31 02:17
@atticusginsborg Changes in that PR were merged to staging few minutes back. I used the admin dashboard to unselect and then select you as an admin (not sure whether that did the trick - changes via UI don't persist). 

Anyways, You can also test whether you have elevated privileges in the staging hub - https://data8-staging.datahub.berkeley.edu/. We will merge the changes into prod

**Comment by atticusginsborg** [comment] 2024-01-31 05:43
Hi @balajialg sorry for the late night response. Since your last message I've gained access; however, some staff seemingly have lost it like Kelsey Ley who I've confirmed had it earlier today. Also, when I closed jupyterhub and reopened I lost admin access again. However, after I logged out and reauthenticated I got it back. Not really sure why that would happen but happy to help you fix it just let me know what you need me to do. This isn't especially timely because as long as a few staff have admin they can open up student's notebooks but it's nice to make sure everyone has access eventually that way anyone can access a student's notebook if needed in office hours.

**Comment by ryanlovett** [comment] 2024-01-31 07:13
@atticusginsborg Elevated privileges were granted via roles in this PR, and full admin was separately removed. All course staff should now have elevated privileges, without having full admin. (Full admin can do things like shut the hub down.) The elevated privileges take effect for each person after they log out and back in again. The logout/login only has to be done once after this PR was merged.

Note that a log out is not the same as closing the browser tab with datahub, or stopping the server. One must visit https://data8.datahub.berkeley.edu/hub/home and click Logout, or visit https://data8.datahub.berkeley.edu/hub/logout directly.
