### ISSUE TITLE
jupyterlab-git integration setup for ESPM-157

### ISSUE THREAD

**Issue by cboettig** [berkeley-dsep-infra/hubs#5826] opened 2024-06-30 04:03 UTC
### Package Name

jupyterlab-git extension

### Hub URL

datahub.berkeley.edu

### Course Name

ESPM-157

### Semester Details

Fall 2024

### Installation Deadline

Start of semester

**Comment by balajialg** [comment] 2024-07-01 23:48
@cboettig Thanks, Is this a duplicate of https://github.com/berkeley-dsep-infra/datahub/issues/5513 where you highlighted that gh-scoped-creds needs to be enabled for Datahub?

**Comment by cboettig** [comment] 2024-07-11 16:32
Sorry I was too terse in the template issue.  I think this is different, I'd like students to be able to use https://github.com/jupyterlab/jupyterlab-git?tab=readme-ov-file#jupyterlab-git GUI, which I think is a distinct dependency from https://github.com/jupyterhub/gh-scoped-creds

**Comment by balajialg** [comment] 2024-07-11 23:49
@cboettig Thanks, that's helpful to know!

**Comment by balajialg** [comment] 2024-07-26 00:19
@cboettig This is currently enabled in https://staging.datahub.berkeley.edu along with gh-scoped-creds requested in #5513!

**Comment by balajialg** [comment] 2024-07-31 17:39
Closing this issue as the changes got merged to prod

**Closed as completed by balajialg** 2024-07-31 17:39 UTC
Labels: package-request
