### ISSUE TITLE
Ischool hub returning 404 error

### ISSUE THREAD

**Issue by balajialg** [berkeley-dsep-infra/hubs#4927] opened 2023-08-24 17:12 UTC
### Bug description

Ischool hub returns a 404 error now. @d-alex-hughes reported that it was working fine till last Wednesday

**Message from Alex Hughes:**
Hey there [@Balaji Alwar](https://ucbischool.slack.com/team/U0294TR1L06)! We’re back at it again! Another semester begins! Thanks to the team for doing the work on the scheduled maintenance over the last week. Since the maintenance window closed, we’re getting TOTAL 404 on the [ischool.datahub.berkeley.edu](http://ischool.datahub.berkeley.edu/) machines. Is there something unplugged on that resource?

### Environment & setup

- Hub: Ischool
- Language: R

### How to reproduce

1. Launch https://ischool.datahub.berkeley.edu/
2. It will return a 404 error

**Comment by balajialg** [comment] 2023-08-24 17:14
Grafana report during the last 30 days,

![image](https://github.com/berkeley-dsep-infra/datahub/assets/2306166/ad4a7708-8f38-4420-a7a6-91e2dd242235)

**Comment by shaneknapp** [comment] 2023-08-24 17:16
@d-alex-hughes 
https://github.com/berkeley-dsep-infra/datahub/pull/4926

**Comment by balajialg** [comment] 2023-08-24 17:35
https://ischool.datahub.berkeley.edu/ works!

**Comment by ryanlovett** [comment] 2023-08-24 20:59
This was caused by https://github.com/berkeley-dsep-infra/datahub/commit/66f2053fc02aa44011fd7799c248cad21c660530, potentially [an old dependency](https://github.com/berkeley-dsep-infra/datahub/pull/4926/files#diff-fd1cc7ff3ae00d835955e04e457d01143e1a2c7fa710d20c10e298faa0a8f41bL2) being included, and my not testing every hub after the commit which affected all hubs. Fixed by #4926.

**Closed as completed by ryanlovett** 2023-08-24 20:59 UTC
Labels: bug

**Comment by d-alex-hughes** [comment] 2023-08-24 21:46
Confirming -- as Ryan has already said -- that this is up and running for students. Thanks Ryan, Balaji and Shane!
