### ISSUE TITLE
EECS Hub: LaTeX error eurosym.sty not found

### ISSUE THREAD

**Issue by ee120-staff** [berkeley-dsep-infra/hubs#3721] opened 2022-09-09 05:43 UTC
### Bug description

Sorry for yet another issue, but I'm getting 
```
! LaTeX Error: File `eurosym.sty' not found.
```
when trying to export a Jupyter notebook to PDF using otter-grader.
(There might be other latex package issues as well, but this is the error message showing up for the moment)

### Environment & setup

- Hub: EECS Hub 
- Language: Python

### How to reproduce

1. Go to https://eecs.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2FEE120-Course-Staff%2Flab-tones-convolution&urlpath=tree%2Flab-tones-convolution%2Flab1.ipynb&branch=main
2. Run the imports and the bottom grader.export() cell.
3. See the error

**Comment by felder** [comment] 2022-09-09 18:17
Now iftex.sty is missing.

Adding that.

**Comment by ee120-staff** [comment] 2022-09-09 19:01
Thank you so much!

Another question: we recently got 4GB of RAM for EE 120, but I still see "Memory: ____ / 2 GB" in the right-hand corner when I open an nbgitpuller link on the EECS hub. Is the 4GB of RAM just for students (i.e., I shouldn't be concerned about seeing 2GB on my end)?

**Comment by felder** [comment] 2022-09-09 20:31
@ee120-staff Ok it's no longer complaining about fonts, but I now see:

```
There was an error generating your LaTeX
Showing concise error message
============================================================
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.316 \begin{document}
                      
? 
! Emergency stop.
!...............................................  
                                                  
l.316 \begin{document}
                      
No pages of output.
Transcript written on notebook.log.

============================================================

/srv/conda/envs/notebook/lib/python3.9/site-packages/otter/check/notebook.py:326: UserWarning: Could not locate a PDF to include
  warnings.warn("Could not locate a PDF to include")
```

However, not sure if that is a result of me not testing the notebook correctly.  Please test and let me know.  However, I may need assistance with debugging this issue since the error does not seem to directly ndicate a missing font/package.

Regarding, your question about RAM.  @ryanlovett should we expect that GSIs would be included as part of using canvas to determine eligibility for resource increases?

**Comment by ee120-staff** [comment] 2022-09-09 20:52
I'm getting the same error. I know it's not an error with the lab because it works fine on regular Datahub. I'm also not sure what could cause the error.

FYI: I don't need the increased RAM myself; I was just verifying that students would see increased RAM.

**Comment by ryanlovett** [comment] 2022-09-09 20:58
@felder The current mechanism doesn't distinguish between the type of course affiliation, e.g. instructor, observer, ta, student, etc. for the purposes of resource allocation, only for admin privileges. If the user hasn't restarted their server since the configuration change, that could explain why the limit is still 2G.

However, the EECS hub along with a bunch of others was moved from CanvasAuthenticator to GenericAuthenticator [before Fall](https://github.com/berkeley-dsep-infra/datahub/commit/c6fc539b807ce392da936ea789ab00fe87554b6a), meaning it relies on the main hub for auth. The course affiliation is stored in the auth_state so I think while the main hub sees it, the EECS hub may not.

We could address this by:
1. Unsetting config.JupyterHub.authenticator_class in eecs/config/common.yaml, so that is uses the default of CanvasOauthenticator in hub/values. (basically undo the eecs hub change from the linked commit above)
2. Deploy to staging.
3. Have GSI login on staging to test that logins work and that it gets allocated the 4G.
4. Deploy to prod.

**Comment by felder** [comment] 2022-09-09 21:13
Grabbing the hub logs reveals the cause:

```
(/usr/share/texlive/texmf-dist/tex/latex/jknapltx/mathrsfs.sty)kpathsea:make_tex: Invalid fontname `[FandolSong-Regular.otf]/OT', contains '['

*************************************************
* xeCJK warning: "fandol"
*
* Fandol is being set as the default font for CJK text.
* Please make sure it has been properly installed.
*************************************************

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
!
! The font "FandolSong-Regular" cannot be found.
!
! See the fontspec documentation for further information.
!
! For immediate help type H <return>.
!...............................................

l.316 \begin{document}

?
! Emergency stop.
!...............................................

l.316 \begin{document}

No pages of output.
Transcript written on notebook.log.
```

Looks like the same issue as #3719

**Comment by felder** [comment] 2022-09-09 21:25
Also the same as #2714

**Comment by felder** [comment] 2022-09-09 21:25
I'm going to add texlive-lang-chinese and see if that fixes it

**Comment by felder** [comment] 2022-09-09 22:16
Ok I tested this in staging and it works!  Changes deployed to prod.  @ee120-staff can you restart your server and try the test case again?

**Comment by ee120-staff** [comment] 2022-09-09 22:21
Works for me!

**Comment by felder** [comment] 2022-09-09 22:22
ok, I opened a new issue with regard to the RAM, #3733...I'm going to close this one.

**Closed as completed by felder** 2022-09-09 22:22 UTC
Labels: package-request

**Comment by ee120-staff** [comment] 2022-09-09 22:24
Thank you so much!
