### ISSUE TITLE
Otter export failed due to a chinese font Issue!

### ISSUE THREAD

**Issue by andrea2031** [berkeley-dsep-infra/hubs#3719] opened 2022-09-09 04:14 UTC
### Bug description

DATA 100 student found this error yesterday

(/usr/share/texlive/texmf-dist/tex/latex/jknapltx/mathrsfs.sty)kpathsea:make_tex: Invalid fontname `[FandolSong-Regular.otf]/OT', contains '['

*************************************************
* xeCJK warning: "fandol"
* 
* Fandol is being set as the default font for CJK text.
* Please make sure it has been properly installed.
*************************************************

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "FandolSong-Regular" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.316 \begin{document}
                      
? 
! Emergency stop.
!...............................................  
                                                  
l.316 \begin{document}
                      
No pages of output.
Transcript written on notebook.log.

================================================================================
If the error above is related to xeCJK or fandol in LaTeX and you don't require this functionality, try running again with no_xecjk set to True or the --no-xecjk flag.

### Environment & setup

- Hub: Data100
- Language: Python

### How to reproduce

same as #2714 but with newer version of otter grader 4.0.1

**Comment by rohanjha123** [comment] 2022-09-09 18:00
Hey, sorry but students are still running into this issue. Please let me know if you would like me to paste the error log of one of the recent student submissions here.

**Comment by felder** [comment] 2022-09-09 18:33
@rohanjha123 Can you verify that students are encountering this after they restart their server?

Alternatively, can you provide instructions on how to reproduce this issue?

**Comment by rohanjha123** [comment] 2022-09-09 19:20
This issue only seems to effect a few students who post on Ed about it. We tell them to restart their kernel, and they say they have done so. I'm not quite sure how to reproduce the issue as I don't have access to their datahub yet, but I can link their gradescope submission and error message if that helps. Once I get added to the data100 admins, I can go into their datahub and try debugging/reproducing the issue

**Comment by yuvipanda** [comment] 2022-09-09 20:01
@rohanjha123 they would need to start and stop their servers from the control panel (data100.datahub.berkeley.edu/hub/home) rather than just their kernels. Can you ask them to try that?

**Comment by felder** [comment] 2022-09-09 20:05
@rohanjha123 I'm working on servicing a number of issues including the admin access for you.  So you should get that pretty soon.

Assuming the server restarts do not work, instructions to reproduce should assist us greatly in making sure the issue is solved.

Also one thing to note is that this issue tracker is public.  So any information you place here should be information that it's ok to share publicly.

**Comment by rohanjha123** [comment] 2022-09-09 23:37
After looking at the student submission closely, we managed to find that the student included a reference to an image that didn't exist on the datahub. This caused the LaTeX to crash, outputting the Fandol font error. However, there was nothing actually wrong with the font - it seems like LaTeX just outputs that error when anything breaks, causing the Fandol font to be a red herring for other issues. We fixed the issue by deleting the non-existent image from the student notebook.

**Comment by felder** [comment] 2022-09-10 00:47
Since @rohanjha123 said multiple students seemed to be impacted by this and it wasn't immediately clear if they had done server restarts, I suggested he keep this ticket open and examine any remaining issues on a case by case basis to see if there is anything actionable by us.

I'll revisit this issue early next week and likely close it.

**Comment by felder** [comment] 2022-09-13 21:46
Going to assume all is well here.  Please reopen this issue if otter export still no workie.

**Closed as completed by felder** 2022-09-13 21:46 UTC
Labels: bug
