### ISSUE TITLE
Berkeley Projects

### ISSUE THREAD

**Issue by WonshilPark** [berkeley-dsep-infra/hubs#3977] opened 2022-11-30 02:19 UTC
### Email Id

wonspark@berkeley.edu

### Link to Datahub Folder

gs://ucb-datahub-archived-homedirs/2022-2-summer/datahub/wonspark.tar.gz

**Comment by felder** [comment] 2022-11-30 18:37
Duplicate of #3976

**Closed as completed by felder** 2022-11-30 18:37 UTC
Labels: support
