### ISSUE TITLE
Admin access request for PHW 251

### ISSUE THREAD

**Issue by madelineadee** [berkeley-dsep-infra/hubs#5000] opened 2023-09-06 06:26 UTC
### Your Name

Madeline Adee

### Affiliated Course Name

PHW 251

### Bcourses Id

1525339

### Role

Lead GSI

### Name of the Hub

- public health datahub

### End Date

-  12/31/23

**Comment by balajialg** [comment] 2023-09-06 17:35
Closing this issue as it is a duplicate of #4995!

**Closed as completed by balajialg** 2023-09-06 17:35 UTC
Labels: support
