### ISSUE TITLE
Files Disappearing 

### ISSUE THREAD

**Issue by madelineadee** [berkeley-dsep-infra/hubs#3292] opened 2022-03-07 02:01 UTC
### Bug description

I was using the datahub for STAT 159/259, had created a folder with a homework assignment (created initially by cloning a git repo), had worked on the homework and saved it many times. Got up from computer for a while and came back and the folder and all contents were gone. Screenshots below taken at the same time show that the "homework" folder was showing edits a few hours ago, but when that folder was opened an entire folder with all files (and git repository) inside of it was gone (with the most recent edits being to files in a different folder many days ago).
<img width="643" alt="Screen Shot 2022-02-22 at 6 07 58 AM" src="https://user-images.githubusercontent.com/98361389/156954921-3f1f32e2-5e64-4669-a64f-01a066e0a532.png">
<img width="1164" alt="Screen Shot 2022-02-22 at 6 04 54 AM" src="https://user-images.githubusercontent.com/98361389/156954929-8e73bc89-36da-451a-a1a5-4c572c25bd22.png">
 

### Environment & setup

- Hub: Datahub for STAT 159/259
- Language: Python

### How to reproduce

Not sure how to reproduce.

**Comment by balajialg** [comment] 2022-03-07 19:41
@madelineadee Ah, that sucks big time. Sorry that you had to go through this issue! Did you experience this yesterday? There is also a [bug ](https://github.com/jupyterlab/jupyterlab/issues/12154) raised with the Jupyter Lab folks who may also have a point of view on this

@yuvipanda @felder Despite [disabling RTC in Stat 159 hub](https://github.com/berkeley-dsep-infra/datahub/pull/3287), this issue seems to persist. Any suggestions on the way forward?

**Comment by yuvipanda** [comment] 2022-03-07 19:44
I'm sorry this happened, @madelineadee! Can you tell us when this happened? 

/cc @fperez.

**Comment by madelineadee** [comment] 2022-03-07 19:46
Yes, it happened on 2/22 - I discussed with @fperez last week in class and he asked me to report the issue (apologies for the delay).

**Comment by balajialg** [comment] 2022-03-07 20:41
@madelineadee Can you check again whether this issue persists? There was a fix for this issue that got deployed 5 days back. Hopefully, this should not be an issue now 

On other note, it would be great if you could also highlight timeline for an issue whenever you raise one!

**Comment by fperez** [comment] 2022-03-08 00:31
Thank you very much @madelineadee for filing this detailed report! I hope the change we made of disabling RTC (very much informed by your comments to me about this incident last week) will take care of the problem for the class. We're tracking the root cause of the problem with folks in the Jupyter team, and I'm experimenting with RTC on a separate hub.

But for now we will leave RTC disabled in the 159/259 hub to avoid taking any risks with student work.

@yuvipanda @balajialg  - I'm pretty sure after the RTC disabling we're fine on this front, but I'm glad to have @madelineadee's report for extra details that may help the Lab team track this down. This particular failure is a bit different from others we've seen (corrupted notebooks and zeroed-out files), so it's good to have the details here.  But I think for now we're good on the campus hub front, thanks so much for the prompt response!

**Comment by madelineadee** [comment] 2022-03-08 01:19
Ι have not had this issue in the last 5 days but will let you know (more promptly!) if it happens again. I'm glad there has been a fix! Thanks for the fast response and feedback on providing specific dates/times - I will make sure to do that in the future.

**Comment by yuvipanda** [comment] 2022-03-08 02:54
Thanks for the report + details, @madelineadee. I'll close this for now, and let's re-open it if the issue recurs?

Thanks a lot for being on top of this, @fperez!

**Closed as completed by yuvipanda** 2022-03-08 02:54 UTC
Labels: bug

**Comment by balajialg** [comment] 2022-03-08 06:26
Thanks, @madelineadee, and @fperez for the detailed inputs!
