### ISSUE TITLE
Request more RAM for class UGBA88

### ISSUE THREAD

**Issue by Montereytony** [berkeley-dsep-infra/hubs#5067] opened 2023-09-26 00:26 UTC
Please double the ram for ongoing UGBA88 using https://datahub.berkeley.edu.  Currently students are having problems at 1G please double it so they can see if that is enough.
Thank you!

**Comment by balajialg** [comment] 2023-09-26 17:19
@Montereytony Thanks! Can you please create a new ticket using [this template](https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=balajialg&labels=support&projects=&template=higher-resources.md&title=Request+more+RAM+for+class+X) or update this ticket with relevant information? We need bcourses id for this course to bump up the resources

**Comment by balajialg** [comment] 2023-09-27 00:43
This is duplicate of #5071

**Closed as completed by balajialg** 2023-09-27 00:43 UTC
Labels: support

**Comment by Montereytony** [comment] 2023-09-27 00:53
Sorry, I do not know what I am doing, has the class been updated?

**Comment by ryanlovett** [comment] 2023-09-27 01:06
Hi @Montereytony , nothing has been updated yet. Please click @balajialg 's "this template" link a couple of comments back on this thread, which is the same destination as going to https://github.com/berkeley-dsep-infra > Issues > New issue > "RAM Request". This is slightly different than doing what you did here since the link that Balaji provided solicits specific information. This reduces the time it takes to change the hub configuration, and also enables the datahub staff to more easily gather data about service requests.

**Comment by Montereytony** [comment] 2023-09-27 02:47
Thank you Ryan, I looked for the submit this and filled out the form. It
seems like this is the third time I am doing the same form.
--Tony
