### ISSUE TITLE
strange automatic file naming and trouble accessing github repo from datahub

### ISSUE THREAD

**Issue by duncancallaway** [berkeley-dsep-infra/hubs#4984] opened 2023-09-01 16:33 UTC
### Bug description

Many of my students are having trouble accessing files in my course github repo.  And when they do, the file names seem to get appended with the date/time they were accessed.  See screenshots below.  My repo is 

https://github.com/duncancallaway/ER131_2023/

And I'm having them access the repo from datahub with this link:  

http://datahub.berkeley.edu/user-redirect/interact?account=duncancallaway&repo=ER131_2023&branch=main&path=

![Screen Shot 2023-08-31 at 6 47 08 PM](https://github.com/berkeley-dsep-infra/datahub/assets/11277405/abafee11-ba80-4d00-ae3b-288f3d005811)
![Screen Shot 2023-08-31 at 6 46 48 PM](https://github.com/berkeley-dsep-infra/datahub/assets/11277405/591405bd-2a39-4431-9ec9-516f9bfaf60e)

### Environment & setup

- Hub: Datahub
- Language: Python

### How to reproduce

Click the interact link in the message above.

**Comment by balajialg** [comment] 2023-09-01 19:34
@duncancallaway The merge conflict issue happens when the instructor makes changes to the git repository after releasing the assignments to students. Students can rename/delete their local existing folder, [restart their server](https://ds-modules.github.io/curriculum-guide/faq/troubleshoot.html?highlight=restart#restarting-servers), and click on the nbgitpuller link which will bring a fresh clone of the assignments to their Datahub instance. 

One other long-term suggestion is to not make any changes to the repository once the link gets distributed to the students. (If the instructor did not make any changes then that needs to be debugged). The issue is caused when the original repository maintained by the instructor and the student repository undergoes changes simultaneously. Nbgitpuller is designed this way in order to avoid overwriting student changes with instructor changes and hence this error message shows up. For more details, refer to the 3rd bullet point in this [documentation](https://ds-modules.github.io/curriculum-guide/technology/jupyter/troubleshoot-nbgitpuller.html?highlight=troubleshoot).

We tried reproducing the timestamp issue but couldn't do it at our end. Do you want to connect via Zoom and debug this issue together @duncancallaway?

**Comment by duncancallaway** [comment] 2023-09-01 19:38
a zoom chat would be really helpful -- are you free next Tuesday between 3
and 5?

Duncan

--------------------------------------------------------------------------------------
Duncan Callaway (he/him), ***@***.***
UC Berkeley, Ohlone Landscape <https://cejce.berkeley.edu/ohloneland>
Research meetings and office hours <http://bit.ly/duncanappt_Fa22>
--------------------------------------------------------------------------------------

**Comment by duncancallaway** [comment] 2023-09-01 19:38
oh and by the way thank you so much for your reply -- it helps a lot,
though I still have questions...

Duncan

--------------------------------------------------------------------------------------
Duncan Callaway (he/him), ***@***.***
UC Berkeley, Ohlone Landscape <https://cejce.berkeley.edu/ohloneland>
Research meetings and office hours <http://bit.ly/duncanappt_Fa22>
--------------------------------------------------------------------------------------

**Comment by balajialg** [comment] 2023-09-01 19:45
@duncancallaway Yes, I am free between 4:15 - 5 PM on Tuesday. I just sent a meeting invite.

**Comment by duncancallaway** [comment] 2023-09-01 19:46
thanks!

Duncan

--------------------------------------------------------------------------------------
Duncan Callaway (he/him), ***@***.***
UC Berkeley, Ohlone Landscape <https://cejce.berkeley.edu/ohloneland>
Research meetings and office hours <http://bit.ly/duncanappt_Fa22>
--------------------------------------------------------------------------------------

**Comment by ericvd-ucb** [comment] 2023-09-01 23:40
Sorry you are having this problem - especially in week 1!
I think that this is probably a time to use the git stash in the Balaji referenced at the terminal
The problem not reproducing for us indicates that its only if someone has pulled before
Which is addressed in the git merge conflict documentation 


<img width="704" alt="image" src="https://github.com/berkeley-dsep-infra/datahub/assets/30128480/74fddb56-4782-4cd9-8ffa-e3d1f2c6d275">

**Comment by balajialg** [comment] 2023-09-06 17:20
@duncancallaway Closing this issue based on our conversation yesterday. Please reopen this issue if you still have any open issues that need to be resolved!

**Closed as completed by balajialg** 2023-09-06 17:20 UTC
Labels: bug
